Repository Coding-Coach/coding-coach, pull requests merged in 2019-01, with the labels that each got.

#221 First approach Report Abuse
  README.md
  UX/README.md
  UX/jpg/reportAbuse.jpg
Labels: Need reviewers, UX

#270 Add mailing list modal to landing page (#269)
  public/index.html
Labels: Need reviewers, Ready for review

#249 Feature/migrate modal styles to tail wind
  src/components/modal/Modal.js
  src/components/modal/modal.module.scss
  tailwind.js
Labels: Need reviewers, Refactor, good first issue

#253 Migrate cookie overlay styles
  src/components/overlayCookie/OverlayCookie.js
  src/components/overlayCookie/overlayCookie.module.scss
Labels: Feature, Need reviewers

#180 tests: test Node.js 8, 10 and 11 (stable)
  .travis.yml
Labels: Blocked, On hold

#266 Forgot Password
  src/components/textfield/TextField.js
  src/components/textfield/__tests__/__snapshots__/TextField.test.js.snap
  src/config/i18n/en/messages.json
  src/config/i18n/es/messages.json
  src/config/i18n/fr/messages.json
  src/containers/App/App.js
  src/pages/auth/ForgotPassword.js
  src/pages/auth/Login.js
  src/pages/auth/Utilities.js
  src/pages/auth/assets/images/forgot-password.svg
  src/pages/index.js
Labels: Feature, In progress, Need reviewers, Refactor

#265 Migrate Button component to tailwind (#232)
  src/components/button/Button.js
  src/components/button/button.module.scss
  src/theme/tailwind.css
  tailwind.js
Labels: In progress, Refactor

#296 [FIX] #288 modal under cookie banner
  src/components/overlayCookie/OverlayCookie.js
Labels: Can be merged

#297 fix: change primary-dark and primary-darker (#292)
  src/config/i18n/en/messages.json
  src/config/i18n/es/messages.json
  src/config/i18n/fr/messages.json
  src/theme/tailwind.css
  tailwind.js
Labels: Needs status update

#268 Remove unused NPM dependencies and add missing peer dependencies
  package.json
  yarn.lock
Labels: In progress, Ready for review
